name: Release
on:
  push:
    branches:
      - semantic-release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Git User
        uses: fregante/setup-git-user@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Codecov
        run: yarn codecov
      - name: Version
        run: yarn version
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish
